apiVersion: v1
kind: Service
metadata:
  name: dish
  labels:
    app: dish
    service: dish
spec:
  ports:
  - port: 9080
    name: http 
  selector:
    app: dish
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtsj-dish
  labels:
    account: dish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-v1
  labels:
    app: dish
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dish
      version: v1
  template:
    metadata:
      labels:
        app: dish
        version: v1
    spec:
      serviceAccountName: mtsj-dish
      containers:
      - name: dish
        image: docker.io/devonmts/mtsj-dish-v1:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080       
---
<<<<<<< HEAD
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-v2
  labels:
    app: dish
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dish
      version: v2
  template:
    metadata:
      labels:
        app: dish
        version: v2
    spec:
      serviceAccountName: mtsj-dish
      containers:
      - name: dish
        image: docker.io/devonmts/mtsj-dish-v2:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080       
---
>>>>>>> a127e3293c29b02fae18b1ec7e4f5a6e6d2386ec
